### ISSUE TITLE
HttpRequest.Builder is not thread-safe

### ISSUE THREAD

**Issue by xhl1988** [StyraInc/opa-kafka-plugin#46]
As a follow up to https://github.com/open-policy-agent/opa/issues/5720, we noticed that the [HttpRequest.Builder](https://github.com/StyraInc/opa-kafka-plugin/blob/main/src/main/scala/org/openpolicyagent/kafka/OpaAuthorizer.scala#L305) inside `AllowCallable` was not thread-safe. Not sure if Guava cache will allow concurrent loading when calling `cache.get(cachableRequest, new AllowCallable(request, opaUrl, allowOnError))`, if yes, then the current implementation might hit the same issue.

**Comment by anderseknert** [comment]
The builder is only ever used in the `call` invocation, so moving the construction of it there seems reasonable to me. PR welcome 🙂

**Comment by anderseknert** [comment]
Fixed in v1.5.1. Thanks for reporting and fixing, @xhl1988!
