### ISSUE TITLE
1.5.1 release doesn't have .jar artifact

### ISSUE THREAD

**Issue by nbuesing** [StyraInc/opa-kafka-plugin#55]
would it be possible to add a .jar artifact for 1.5.1 as it does for 1.5.0?

* It is easier to upgrade the existing pipeline using the 1.5.0 artifact.
* I am having issues building on my M1 Mac.
* some clients frown when 3rd party software has to be built, unfortunately.

If there is another place to find the artifact, that would be great -- I didn't in my maven repo search.

Thank you.

**Comment by anderseknert** [comment]
Hi Neal! Where are you looking for that? It looks like it's published https://central.sonatype.com/artifact/org.openpolicyagent.kafka/opa-authorizer/overview

**Comment by anderseknert** [comment]
Oh, sorry, you're saying it's missing a jar file? I'll take a look at that today then and will let you know when that's fixed.

**Comment by anderseknert** [comment]
I just pulled the jar from https://mvnrepository.com/artifact/org.openpolicyagent.kafka/opa-authorizer/1.5.1 and it looks like everything is in there. Am I missing something @nbuesing? 🙂

**Comment by nbuesing** [comment]
Thank you.

I was looking at the github releases (https://github.com/StyraInc/opa-kafka-plugin/releases) where previous versions included it, but the 1.5.1 did not.

I am now confused why I didn't find it there, but that works for me; sorry about that.

**Comment by nbuesing** [comment]
with it being here, https://mvnrepository.com/artifact/org.openpolicyagent.kafka/opa-authorizer/1.5.1 - closing issue

**Comment by anderseknert** [comment]
Ah, yes, the release process here has been rather manual, I'm afraid. I'll make sure to add the jar to GitHub too for completeness. Thanks!
